// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF8tkKew2_sGDLlXO-AcqSt_U1N5Fj5fk',
    appId: '1:475546672000:web:089741e5ea83bbe92b7f65',
    messagingSenderId: '475546672000',
    projectId: 'car-app-2025',
    authDomain: 'car-app-2025.firebaseapp.com',
    storageBucket: 'car-app-2025.firebasestorage.app',
    measurementId: 'G-8EPXDRQRQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCztISRH92jGjWbncnbensPApWWxjjl26M',
    appId: '1:475546672000:android:6e2ee6341621d0322b7f65',
    messagingSenderId: '475546672000',
    projectId: 'car-app-2025',
    storageBucket: 'car-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcCsHvGHD5FaPCXH9jQWcZFfmiJEWIeJE',
    appId: '1:475546672000:ios:7f4605b0d445f94c2b7f65',
    messagingSenderId: '475546672000',
    projectId: 'car-app-2025',
    storageBucket: 'car-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.carapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcCsHvGHD5FaPCXH9jQWcZFfmiJEWIeJE',
    appId: '1:475546672000:ios:7f4605b0d445f94c2b7f65',
    messagingSenderId: '475546672000',
    projectId: 'car-app-2025',
    storageBucket: 'car-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.carapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF8tkKew2_sGDLlXO-AcqSt_U1N5Fj5fk',
    appId: '1:475546672000:web:1b4f8cbc3a0cb7882b7f65',
    messagingSenderId: '475546672000',
    projectId: 'car-app-2025',
    authDomain: 'car-app-2025.firebaseapp.com',
    storageBucket: 'car-app-2025.firebasestorage.app',
    measurementId: 'G-10B9G2N177',
  );

}